### ISSUE TITLE
ReadTheDocs link in README leads to 404 page

### ISSUE THREAD

**Issue by hawkw** [yarbroughw/JMDE#3]
I'm not sure if this documentation is finished yet or not, but if it is, you should be aware that following the link gives me this:

<img width="878" alt="screen shot 2015-08-04 at 7 24 15 pm" src="https://cloud.githubusercontent.com/assets/2796466/9075074/7b9d6dd8-3ade-11e5-893c-6edafdad8dd3.png">

**Comment by yarbroughw** [comment]
Haha thanks. This project has been pretty minimally worked on since I submitted my comp. Documentation is sorely needed, as well as some major refactors that I'll make other issues for.

**Comment by hawkw** [comment]
Oh okay, that makes sense. I just figured I'd check, since the link is there.
